dishes = {
    # Tofu(vegan) Dishes
    ('tofu(vegan)', 'grilled', 'salty', '500'): 'Grilled Tofu with Savory Glaze',
    ('tofu(vegan)', 'grilled', 'sweet', '700'): 'Sweet Chili Glazed Grilled Tofu',
    ('tofu(vegan)', 'stir-fried', 'spicy', '900'): 'Spicy Stir-Fried Tofu with Veggies',
    ('tofu(vegan)', 'baked', 'sour', '1200'): 'Baked Tofu with Tangy Citrus Sauce',
    ('tofu(vegan)', 'steamed', 'salty', '500'): 'Steamed Tofu in Salty Ginger Broth',
    ('tofu(vegan)', 'stir-fried', 'sweet', '700'): 'Sweet Ginger Tofu Stir-Fry',
    ('tofu(vegan)', 'baked', 'spicy', '900'): 'Spicy Baked Tofu with Tomato Sauce',
    ('tofu(vegan)', 'steamed', 'sour', '500'): 'Steamed Tofu with Sour Plum Sauce',
    ('tofu(vegan)', 'grilled', 'salty', '1200'): 'Grilled Tofu with Salty Miso Glaze',
    ('tofu(vegan)', 'baked', 'sweet', '700'): 'Baked Tofu with Sweet Sesame Glaze',
    ('tofu(vegan)', 'stir-fried', 'salty', '1200'): 'Salty Black Bean Tofu Stir-Fry',
    ('tofu(vegan)', 'baked', 'sour', '700'): 'Baked Tofu with Sour Lemon Drizzle',
    ('tofu(vegan)', 'steamed', 'spicy', '900'): 'Steamed Spicy Tofu with Chili Flakes',
    ('tofu(vegan)', 'grilled', 'sweet', '500'): 'Grilled Tofu with Sweet Mango Salsa',
    ('tofu(vegan)', 'stir-fried', 'sour', '700'): 'Sour Tofu Stir-Fry with Pineapple',
    ('tofu(vegan)', 'baked', 'spicy', '500'): 'Spicy Baked Tofu with Sriracha',
    ('tofu(vegan)', 'steamed', 'sweet', '900'): 'Sweet Steamed Tofu with Agave Syrup',
    ('tofu(vegan)', 'grilled', 'sour', '1200'): 'Grilled Tofu with Sour Apple Glaze',
    ('tofu(vegan)', 'stir-fried', 'salty', '700'): 'Salty Stir-Fried Tofu with Soy Sauce',
    ('tofu(vegan)', 'baked', 'sour', '500'): 'Baked Tofu with Zesty Lime Sauce',
    # Chicken Dishes
    ('chicken', 'grilled', 'sweet', '700'): 'Honey Glazed Grilled Chicken',
    ('chicken', 'stir-fried', 'spicy', '500'): 'Spicy Chicken Stir-Fry with Peppers',
    ('chicken', 'baked', 'sour', '900'): 'Sour Lime Baked Chicken Breast',
    ('chicken', 'steamed', 'salty', '1200'): 'Soy Garlic Steamed Chicken',
    ('chicken', 'grilled', 'spicy', '700'): 'Grilled Chicken with Spicy Rub',
    ('chicken', 'stir-fried', 'sour', '900'): 'Stir-Fried Chicken with Lemon Sauce',
    ('chicken', 'baked', 'spicy', '500'): 'Spicy Baked Chicken with Hot Sauce',
    ('chicken', 'steamed', 'sweet', '700'): 'Sweet Steamed Chicken with Honey',
    ('chicken', 'grilled', 'sour', '1200'): 'Grilled Chicken with Tart Cherry Sauce',
    ('chicken', 'stir-fried', 'salty', '700'): 'Salty Soy Chicken Stir-Fry',
    ('chicken', 'baked', 'salty', '700'): 'Salty Baked Chicken with Olive Tapenade',
    ('chicken', 'steamed', 'spicy', '900'): 'Steamed Spicy Chicken with Hot Sauce',
    ('chicken', 'grilled', 'sweet', '500'): 'Sweet BBQ Grilled Chicken',
    ('chicken', 'stir-fried', 'spicy', '1200'): 'Hot and Spicy Chicken Stir-Fry',
    ('chicken', 'baked', 'sour', '700'): 'Baked Chicken with Tart Lemon Sauce',
    # Beef Dishes
    ('beef', 'grilled', 'sour', '900'): 'Grilled Beef with Sour Balsamic Glaze',
    ('beef', 'stir-fried', 'sweet', '500'): 'Sweet and Spicy Beef Stir-Fry',
    ('beef', 'baked', 'salty', '700'): 'Salty Herb-Crusted Baked Beef',
    ('beef', 'steamed', 'spicy', '1200'): 'Steamed Spicy Beef with Chili Sauce',
    ('beef', 'grilled', 'sweet', '500'): 'Grilled Beef with Sweet Teriyaki Sauce',
    ('beef', 'baked', 'sour', '500'): 'Baked Beef with Sour Cream and Chives',
    ('beef', 'steamed', 'sweet', '900'): 'Sweet Steamed Beef with Maple Glaze',
    ('beef', 'grilled', 'spicy', '700'): 'Grilled Spicy Pepper Beef',
    ('beef', 'stir-fried', 'salty', '1200'): 'Salty Black Pepper Beef Stir-Fry',
    ('beef', 'baked', 'sweet', '500'): 'Sweet Baked Beef with Caramelized Onions',
    ('beef', 'steamed', 'salty', '500'): 'Salty Steamed Beef with Soy Sauce',
    ('beef', 'grilled', 'sour', '900'): 'Grilled Beef with Sour Mustard Glaze',
    ('beef', 'stir-fried', 'sweet', '700'): 'Sweet Beef Stir-Fry with Brown Sugar',
    ('beef', 'baked', 'spicy', '1200'): 'Spicy Baked Beef with Chili Rub',
    ('beef', 'steamed', 'sour', '700'): 'Steamed Beef with Sour Tamarind Sauce',
    # Pork Dishes
    ('pork', 'grilled', 'spicy', '700'): 'Spicy Grilled Pork Ribs',
    ('pork', 'stir-fried', 'sour', '500'): 'Sour Pork Stir-Fry with Tamarind',
    ('pork', 'baked', 'sweet', '900'): 'Baked Pork with Honey Mustard Glaze',
    ('pork', 'steamed', 'salty', '1200'): 'Steamed Pork with Salty Soy Sauce',
    ('pork', 'grilled', 'salty', '700'): 'Grilled Pork with Savory Garlic Marinade',
    ('pork', 'steamed', 'spicy', '700'): 'Steamed Spicy Pork with Ginger Sauce',
    ('pork', 'grilled', 'sweet', '500'): 'Grilled Pork with Sweet Apple Glaze',
    ('pork', 'stir-fried', 'salty', '900'): 'Salty Pork Stir-Fry with Soy and Garlic',
    ('pork', 'baked', 'sour', '1200'): 'Sour Baked Pork with Vinegar Sauce',
    ('pork', 'steamed', 'sour', '700'): 'Steamed Pork with Sour Orange Sauce',
    ('pork', 'grilled', 'salty', '500'): 'Salty Grilled Pork with Herbs',
    ('pork', 'stir-fried', 'sweet', '900'): 'Sweet and Sour Pork Stir-Fry',
    ('pork', 'baked', 'spicy', '700'): 'Spicy Baked Pork with Hot Mustard',
    ('pork', 'steamed', 'salty', '1200'): 'Steamed Pork with Salty Bean Sauce',
    ('pork', 'grilled', 'sour', '700'): 'Grilled Pork with Sour Cherry Glaze',
}
   


